server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: http://localhost:8081/
          predicates:
            - Path=/api/first/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - name: RateLimiterCustomFilter
              args:
                maxAllowedRequestsPerPeriod: 5
                timePeriodInSeconds: 60
        - id: secondModule
          uri: http://localhost:8082/
          predicates:
            - Path=/api/second/**
          filters:
            - AddRequestHeader=second-request, second-request-header
            - name: RateLimiterCustomFilter
              args:
                maxAllowedRequestsPerPeriod: 5
                timePeriodInSeconds: 60